### PR TITLE
add styling for aboutUs navbar and added styling for active link on mainNavbar

### PR DESCRIPTION
**Pull request by mhema42**
Fix navbar on aboutUs with styling, plus small change for active links in styling for mainNavbar.
(also change pathname in link for /aboutus to /aboutus/history in mainNav, so that aboutus/history is active when you enter aboutus)

Maybe there should be a slightly bigger difference in color on mainNav for active/inactive link?  

image

### CODE REVIEW

**Review by Nw84 — CHANGES_REQUESTED** [review]
Nicely done and i think that it was a smart solution to use ternary operators and useRouter() to handle the active link navigation.  

But it seems like you have forgotten to add styles for the Main Navigation in the MainNavigation.module.css, so the a tags that are not active has class undefined when i inspect it.  And maybe we should also add a black or gold line under the active link in the main navigation so that it is more clear which side that you are on. 

the import { useRouter } is also imported from 'next/dist/client/router' instead from 'next/router' . I dont know if that makes any difference, but the nextjs documentation says that it should be imported from 'next/router' and i think that the other is added with completion from visual studio code for some reason ?

**Review by mhema42 — COMMENTED** [review]
Fixed requested changes

**Review by Nw84 — APPROVED** [review]
Works like a charm! Good job 👍

**Review by emmaambr — APPROVED** [review]
Work really well, great job Mats! 💯

**Pull request merged**
